### ISSUE TITLE
Show using address instead of lat, lng

### ISSUE THREAD

**Issue by Dellybro** [LucasMonteiro1/react-native-open-map#9]
Is it possible to show using an address string rather then a lat and lng?

**Comment by arelstone** [comment]
That should be straight forward. What I am doing is parsing the title-option as the address i want to have displayed

**Like this:**

```js
return OpenMap.show({
        latitude: location.lat,
        longitude: location.lng,
        title: data.name || data.fullAddress,
    })
```

Hope this helps

**Comment by LucasMonteiro1** [comment]
@Dellybro you can try return lat lng with [Google Geocoding API](https://developers.google.com/maps/documentation/geocoding/intro) before call `OpenMap.show({})`.
